name: su-ai-chatbot

services:
  worker:
    build:
      context: .
      args:
        - NVIDIA_VISIBLE_DEVICES=all
    image: su-ai-chatbot
    container_name: su-ai-chatbot
    networks:
      - reverse-proxy
    volumes:
      - /mnt/linux/docker/su-ai-chatbot:/su-ai-chatbot
    environment:
      TZ: Asia/Tokyo
    # ports:
    #   - 7860:7860
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    restart: unless-stopped
    labels:
      - sablier.enable=true
    healthcheck:
      test: ["CMD", "curl", "-fsSI", "http://localhost:7860"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 1m
      start_interval: 1s
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

networks:
  reverse-proxy:
    external: true
