name: su-ai-chatbot

services:
  worker:
    build:
      context: .
    image: su-ai-chatbot
    container_name: su-ai-chatbot
    networks:
      - reverse-proxy
    volumes:
      - /mnt/linux/docker/su-ai-chatbot:/su-ai-chatbot
    environment:
      TZ: Asia/Tokyo
    # ports:
    #   - 7860:7860
    restart: unless-stopped
    labels:
      - sablier.enable=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

networks:
  reverse-proxy:
    external: true
