[project]
name = "su-ai-chatbot"
version = "0.1.0"
description = ""
authors = [{ name = "ngoc", email = "ngochust56@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13,<4.0"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
gradio = "^5.31.0"
langchain = "^0.3.25"
langchain-qdrant = "^0.2.0"
torch = "^2.7.0"
accelerate = "^1.7.0"
python-dotenv = "^1.1.0"
transformers = "^4.52.3"
langchain-huggingface = "0.1.2"
bitsandbytes = "^0.45.5"
qdrant-client = "^1.14.2"
sentence-transformers = "^4.1.0"
sentencepiece = {git = "https://github.com/google/sentencepiece.git", subdirectory = "python"}
langchain-community = "^0.3.24"
beautifulsoup4 = "^4.13.4"
lxml = "^5.4.0"
grandalf = "^0.8"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
