[project]
name = "su-ai-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "accelerate>=1.10.0",
    "beautifulsoup4>=4.13.4",
    "bitsandbytes>=0.46.1",
    "gradio>=5.42.0",
    "grandalf>=0.8",
    "huggingface-hub>=0.34.4",
    "langchain>=0.3.27",
    "langchain-community>=0.3.27",
    "langchain-huggingface>=0.3.1",
    "langchain-ollama>=0.3.6",
    "langchain-openai>=0.3.29",
    "langchain-qdrant>=0.2.0",
    "llama-cpp-python>=0.3.34",
    "lxml>=6.0.0",
    "psycopg2-binary>=2.9.10",
    "pytest>=9.1.1",
    "python-dotenv>=1.1.1",
    "qdrant-client>=1.15.1",
    "sentence-transformers>=5.1.0",
    "sentencepiece>=0.2.0",
    "sqlalchemy>=2.0.42",
    "torch>=2.8.0",
    "transformers>=4.55.0",
]

[[tool.uv.index]]
name = "llama-cpp-python-wheel"
url = "https://abetlen.github.io/llama-cpp-python/whl/cu132"
explicit = true

[tool.uv.sources]
llama-cpp-python = { index = "llama-cpp-python-wheel" }

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
    "pyright>=1.1.411",
    "ruff>=0.12.8",
]
